---
name: Dependency Review

on:
  workflow_call:
    inputs:
      runs-on:
        description: The type of runner to use
        required: false
        type: string
        default: ubuntu-24.04

permissions: {}

concurrency:
  group: ${{ format('{0}-{1}-{2}-{3}-{4}', github.workflow, github.event_name, github.ref, github.base_ref, github.head_ref) }}
  cancel-in-progress: true

env:
  DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG || vars.ACTIONS_RUNNER_DEBUG || secrets.ACTIONS_STEP_DEBUG || vars.ACTIONS_STEP_DEBUG || false }}

jobs:
  dependency-review:
    name: 🔀 Dependency Review
    if: ${{ github.repository_visibility == 'public' && (github.event_name == 'pull_request' && !github.event.pull_request.draft && !contains(fromJSON('["closed", "converted_to_draft"]'), github.event.action)) }}
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 15
    steps:
      - name: 🩺 Debug
        if: ${{ env.DEBUG == 'true' }}
        uses: raven-actions/debug@9dbdeb7eea607a7d73411895c65987e71d59a466 # v1.2.0
        with:
          vars-context: ${{ toJson(vars) }}
          needs-context: ${{ toJson(needs) }}
          inputs-context: ${{ toJson(inputs) }}

      - name: ⤵️ Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ github.token }}
          persist-credentials: false

      - name: 🔀 Dependency Review
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          repo-token: ${{ github.token }}
          vulnerability-check: true
          license-check: true
          comment-summary-in-pr: true
