---
name: Publish Release

on:
  workflow_call:
    inputs:
      runs-on:
        description: The type of runner to use
        required: false
        type: string
        default: ubuntu-latest
      tag-name:
        description: Tag name that the major tag will point to
        type: string
        required: true
      prerelease:
        description: Whether to create a pre-release or not
        required: false
        type: boolean
        default: false
    outputs:
      id:
        description: Release ID
        value: ${{ jobs.gh-release.outputs.id }}
      url:
        description: URL to the Release HTML Page
        value: ${{ jobs.gh-release.outputs.url }}
      upload_url:
        description: URL for uploading assets to the release
        value: ${{ jobs.gh-release.outputs.upload_url }}
      major_tag:
        description: "The major version tag that has been updated (created). Examples: v1, 1"
        value: ${{ jobs.gh-release.outputs.major-tag }}

jobs:
  gh-release:
    name: GitHub Release
    outputs:
      id: ${{ steps.gh-release.outputs.id }}
      url: ${{ steps.gh-release.outputs.url }}
      upload_url: ${{ steps.gh-release.outputs.upload_url }}
      major_tag: ${{ steps.major-tag.outputs.major-tag }}
    # permissions:
    #   contents: write
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Get GitHub App Token
        uses: wow-actions/use-app-token@v2
        id: get-token
        with:
          app_id: ${{ secrets.ORG_BOT_APP_ID }}
          private_key: ${{ secrets.ORG_BOT_PRIVATE_KEY }}
          fallback: ${{ github.token }}

      - name: Update release to the latest
        id: gh-release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ inputs.prerelease }}
          token: ${{ steps.get-token.outputs.BOT_TOKEN }}

      - name: Update the major tag to include the ${{ inputs.tag-name }} changes
        id: major-tag
        uses: actions/publish-action@v0.2.2
        with:
          source-tag: ${{ inputs.tag-name }}
          token: ${{ steps.get-token.outputs.BOT_TOKEN }}
